[build]
  publish = "frontend/dist"
  command = "npm install && npx prisma db push --accept-data-loss && npx prisma generate && npx ts-node seed.ts && cd frontend && npm install && npm run build"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
